#!/bin/bash
# Build script for squad-status
# Generates config.js from environment variables for Cloudflare Pages deployment

set -e

echo "🔨 Building squad-status..."

# Check if environment variables are set
if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
    echo "⚠️  WARNING: SUPABASE_URL or SUPABASE_ANON_KEY not set!"
    echo "    Using placeholder values for local development."
    echo "    Set these variables in Cloudflare Pages dashboard for production."
    
    # Use placeholders for local dev
    SUPABASE_URL="${SUPABASE_URL:-https://YOUR_PROJECT.supabase.co}"
    SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-your-anon-key-here}"
fi

# Generate config.js
cat > config.js << EOF
// Auto-generated configuration file
// DO NOT EDIT - This file is generated by build.sh
// Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

const SUPABASE_URL = '${SUPABASE_URL}';
const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
EOF

echo "✅ Generated config.js"
echo "   SUPABASE_URL: ${SUPABASE_URL}"
echo "   SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:0:20}..." # Show only first 20 chars

# Create dist directory if needed (for future expansion)
# Currently we deploy from root, but this allows for future optimization
# mkdir -p dist
# cp index.html timeline-preview.html config.js dist/

echo "🎉 Build complete!"
